name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install golint
      run: go install golang.org/x/lint/golint@v0.0.0-20210508222113-6edffad5e616

    - name: Run Tests
      run: ./run_tests.sh
